name: 'HWC-3'

on:
    push:
        branches: [ "main" ]
    pull_request:

permissions:
    contents: read

jobs:
    build:
        name: 'Build'
        runs-on: ubuntu-latest
        env:
            <placeholder for .env>:
        defaults:
            run:
                shell: bash
        
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Terraform Init
              run: make init

            - name: Terraform Format
              run: make lint

            - name: Terraform Plan
              run: make plan


    deploy:
        name: 'Deploy'
        runs-on: ubuntu-latest
        needs: build
        env:
            <placeholder for .env>:
        defaults:
            run:
                shell: bash
        
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Terraform Init
              run: make init

            - name: Terraform Apply
              run: make apply