name: 'HWC-3'

on:
    push:
        branches: [ "main" ]
    pull_request:

permissions:
    contents: read

jobs:
    build:
        name: 'Build'
        runs-on: self-hosted-rhel-runner
        defaults:
            run:
                shell: bash
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Gather Details
              run: ./scripts/boot.sh

            - name: Terraform Init
              run: make init

            - name: Terraform Format
              run: make lint

            - name: Terraform Plan
              run: make plan


    deploy:
        name: 'Deploy'
        runs-on: self-hosted-rhel-runner
        needs: build
        defaults:
            run:
                shell: bash
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Gather Details
              run: ./scripts/boot.sh

            - name: Terraform Init
              run: make init

            - name : Terraform Format
              run: make lint

            - name: Terraform Apply
              run: make apply