name: 'HWC-3'

on:
    push:
    pull_request:
      branches:
        - '**'

jobs:
  steps:
  checkout:
    - uses: actions/checkout@v4
  
  lint:
    runs-on: self-hosted-rhel-runner
    steps:
      - name: Lint Code
        run: make lint

  build:
    runs-on: self-hosted-rhel-runner
    needs: lint
    steps:
      - name: Build Terraform Plan
        run: |
          make plan
        continue-on-error: true
          
  deploy:
    runs-on: self-hosted-rhel-runner
    needs: build
    environment: non-prod
    steps:
      - name: Deploy with Terraform
        run: make apply

  deploy_prod:
    runs-on: self-hosted-rhel-runner
    needs: deploy
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Request Approval for Production
        run: echo "Approval required for deploying to Production"
        continue-on-error: true
      - name: Deploy to Production
        run: |
          make apply
